
version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "teste123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: ./api
    container_name: cliente-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ClienteDb;User=sa;Password=teste123;
    ports:
      - "5000:80"
    depends_on:
      - sqlserver

  front:
    build:
      context: ./front
    container_name: cliente-front
    ports:
      - "4200:4200"
    command: ["npm", "start"]
    volumes:
      - ./front:/app
    working_dir: /app
    depends_on:
      - api

volumes:
  sql_data:
